### ISSUE TITLE
stripping quotes from array keys

### ISSUE THREAD

**Issue by eurosat7** [thermoweb/yaml-sorter-plugin#1]
Plase do not strip single quotes from array keys, or at least make it optional.
I have keys with problematic chars.

Maybe you even want to add an option to force single quotes for array keys if they contain problematic chars or even always? :D

```
Format of array keys:
[ ] leave as is
[ ] always strip quotes
[ ] strip quotes if save
[ ] never strip quotes
[ ] add quotes if unsave
[ ] always add quotes
```

Some frameworks are forcing you to do that in the near future.

**Comment by thermoweb** [comment]
Could you provide an example ?
